---
title: "Syllabus"
---

-   Downloadable Syllabus [PDF](files/syllabus.pdf)

## Course Description

This course is designed to understand mathematical tools useful for the rest of your Master program, especially for the upcoming, mandatory courses in statistics and game theory. The course reviews some mathematical concepts most of you will be familiar with from high school, such as functions, derivatives, integrals, vectors, matrices and probability distributions. Each day consists of lectures and exercise sessions. The course's objective is to make students familiar and comfortable with notation, reading mathematical statements, and applying various mathematical techniques.

## Attendance Policy

While the instructor strongly encourage attendance, this course is voluntary. If you decide to participate I expect you to attend the class actively and full time each session.

## Class Schedule {#class-schedule}

::: center
| **Date**     | **Day**  | **Time**       | **Room**                         |
|--------------|----------|----------------|----------------------------------|
| 29.08.2025   | Friday   | 09:15–17:15     | B 317 (A5, 6 Bauteil B)         |
| 05.09.2025   | Friday   | 14:00–17:15     | B 317 (A5, 6 Bauteil B)         |
| 12.09.2025   | Friday   | 14:00–17:15     | B 317 (A5, 6 Bauteil B)         |
| 19.09.2025   | Friday   | 14:00–17:15     | B 317 (A5, 6 Bauteil B)         |
| 26.09.2025   | Friday   | 14:00–17:15     | B 317 (A5, 6 Bauteil B)         |
| 10.10.2025   | Friday   | 14:00–17:15     | B 317 (A5, 6 Bauteil B)         |
| 17.10.2025   | Friday   | 14:00–17:15     | B 317 (A5, 6 Bauteil B)         |
:::

## Contents {#contents}

- Introduction
- Set Theory
  - Sets, Binary Relations, Functions
- Analysis I
  - Equations, Differentiation
- Analysis II
  - Optimization, Integration
- Linear Algebra I
  - Linear Combinations, Vector Spaces, Matrices
- Linear Algebra II
  - Determinants, Gaussian Elimination
- Probability I
  - Combinatorics, Bayes' Rule
- Probability II
  - Distributions
